# Generated by Django 5.1 on 2024-08-23 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=123)),
            ],
        ),
        migrations.CreateModel(
            name='ImgFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='media/photo_details')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('price_day', models.PositiveIntegerField()),
                ('img_main', models.ImageField(upload_to='media/logo')),
                ('volume', models.DecimalField(decimal_places=1, max_digits=8)),
                ('power', models.IntegerField()),
                ('fuel_type', models.PositiveSmallIntegerField(choices=[(1, 'Дизель'), (2, 'Бензин'), (3, 'Электро')])),
                ('gearbox', models.PositiveSmallIntegerField(choices=[(1, 'Механика'), (2, 'Автомат')])),
                ('type_car_body', models.PositiveSmallIntegerField(choices=[(1, 'Гибрид'), (2, 'Электро'), (3, 'ДВС')])),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Забронирован'), (2, 'Свободен')])),
                ('year', models.PositiveIntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brandcars')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('detail_img', models.ManyToManyField(to='app.imgfile')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('total_cost', models.PositiveIntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car')),
            ],
        ),
    ]
