# Generated by Django 5.1 on 2024-08-24 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Забронирован'), (2, 'Свободен')], default=1),
        ),
    ]
